### ISSUE TITLE
Freeze panes in SAF files

### ISSUE THREAD

**Issue by JanOdijk** [UUDigitalHumanitieslab/sasta#177]
Add Freeze panes to SAF files so that the header and the first two columns remain visible when scrolling

**Comment by JeltevanBoheemen** [comment]
This has already been implemented: e1121454f1974d54547836a74d57c398538c459a

**Comment by JanOdijk** [comment]
Perfect!
Jan

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
